# Proposal

## Research topic

In our final project, we will perform a rigorous data visualization analysis for the various counting statistics available from the 
2021-2022 NCAA men's basketball season. Such an analysis will seek to make sense of win-loss ratios by finding patterns across offensive 
and defensive analytics, which might show team advantages provided by individually exceptional players or perhaps by a more rounded 
team contribution. Furthermore, an analysis of this data might make sense of differences of competition across school divisions by 
analyzing differences in player and team skill level.

## Data availability

The statistics page of the NCAA (https://stats.ncaa.org/) allows for a very in depth search of individual players and individual teams 
by introducing a large number of search fields. For example, through the website interface, we can input search fields for "Men's Basketball" 
"2021-2022" and "Final Statistics" to start an initial search for the statistics of interest for this project. We can then enter the 
"Individual" tab to start a search for individual player statistics, and then enter a search field for a basketball statistic of choice. 
For example, we might enter "3-pt Field Goal Attempts" which will then populate a table below that retrieves the player name, school, 
school division, player class level, height, basketball position they play, the number of 3-pt Field Goals the player attempted, and the 
rank of the player by the number of 3-pt Field Goals the player attempted (highest to lowest). This table also provides a button to 
download an excel file of the table return of this search.

Other individual search categories include "Assists per Game" (assists are a pass of the basketball to another player that results in 
a score by the passed-to player), "Points per Game", "Blocked Shots per Game", and 24 other counted statics of relevance. 

If we choose to enter the "Team" tab rather than the "Individual" tab to start searches for team statics, not only can we search for 
aggregates of some of the individual player statistics by team, but there are also 5 other statistics available, such as "Win-Loss Margin" 
or "Turn Over Margin" that are game based statics aggregated across the whole teams roster.

Our plan is to individually click through and download every individual statistic and every team statistic create two different 
aggregate datasets.
